import Head from 'next/head'
import Image from 'next/image'
import React from 'react'

const Team = () => {
  return (
    <div className=' '>
        <Head>
          <title>
            Clemmeridian
          </title>
          <meta name="description" content="Generated by create next app"></meta>
        </Head>

         <div className='page-title text-center text-4xl m-24'>
            <h1>THE TEAM</h1>
            <div className='line'></div>
        </div>

        <div className='flex flex-col items-center px-5'>
          <div className='text-center md:w-2/3 mb-5'>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, harum eligendi quisquam recusandae inventore culpa sequi, dolores atque voluptates doloremque minus quidem facere explicabo deserunt, eveniet totam animi vel modi.</p>
          </div>
          <div className='card h-60v md:w-1/3 text-center justify-center'>
            <div className='border-solid w-full h-full'> 
              <Image alt='Clement Isikwe' fill src='/images/together.jpg'/>
            </div>
            <div className='h-20v'>
              <h4 className='font-semibold'>Founder and CEO</h4>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perspiciatis doloremque laborum, sit amet explicabo id repudiandae totam fugiat quod dolorum.</p>
            </div>
          </div>

          <div className='flex flex-wrap gap-5 items-center justify-center mt-10'>
            <div className='card h-60v md:w-1/3 text-center justify-center'>
              <Image alt='Clement Isikwe' width={800} height={300} src='/images/together.jpg'/>
              <div className=' h-20v'>
                <h4 className='font-semibold'>ceo somethin so</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perspiciatis doloremque laborum, sit amet explicabo id repudiandae totam fugiat quod dolorum.</p>
              </div>
            </div>
            <div className='card h-60v md:w-1/3 text-center justify-center'>
              <Image alt='Clement Isikwe' width={800} height={300} src='/images/together.jpg'/>
              <div className=' h-20v'>
                <h4 className='font-semibold' >ceo somethin so</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perspiciatis doloremque laborum, sit amet explicabo id repudiandae totam fugiat quod dolorum.</p>
              </div>
            </div>
          </div>
        </div>

    </div>
  )
}

export default Team